name: Deploy Android & iOS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
            cache: 'npm'

      - run: npm install --legacy-peer-deps

      - run: npm install -g eas-cli

      # Android
      - run: eas build --platform android --non-interactive --profile production --wait
      - run: eas submit --platform android --non-interactive --latest

      # iOS
      - run: eas build --platform ios --non-interactive --profile production --wait
      - run: eas submit --platform ios --non-interactive --latest