name: Deploy Android & iOS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Setup Expo & EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Android
      - name: Build Android
        run: eas build --platform android --non-interactive --profile production --wait

      - name: Submit Android
        run: eas submit --platform android --non-interactive --latest

      # iOS
      - name: Build iOS
        run: eas build --platform ios --non-interactive --profile production --wait

      - name: Submit iOS
        run: eas submit --platform ios --non-interactive --latest